### PR TITLE
Added LICENSE file

### PR DESCRIPTION
**Pull request by jeppefrandsen**

### CODE REVIEW

**Comment by deets** [comment]
Bump

**Comment by fr00b0** [comment]
Hello @jeppefrandsen 

Sorry. I have been neglecting his repo for some time, but I saw your bump.

This pull request named "Added LICENSE file" seems to have 2 commits. Commit number 2 adds `noexcept` to the destructor of `signal_type`
There is also no description describing the reasoning this change? Is it a mistake? I was under the impression that all destructors are implicitly `noexcept` in C++11, so the addition is redundant? (even though I like the expressiveness of the change)

I'm just a little confused of why this change was included in this pull request

**Comment by jeppefrandsen** [comment]
Hi @fr00b0. Sorry. This has been included by mistake as we added this commit last year to our fork to fix a compile issue. Will remove this commit again from this PR 👍🏻

**Comment by jeppefrandsen** [comment]
Will create a new PR

**Pull request closed without merging**
