### PR TITLE
Add Similar Qt5 Class Visibility Definitions

### PR DESCRIPTION
**Pull request by drewr95**
Similar to Qt `qobjectdefs.h`, you can declare in classes:

`public slots:`
`protected slots:`
`private slots:`

and

`signals:`

### CODE REVIEW

**Comment by drewr95** [comment]
@fr00b0 This PR got deleted.  What was the reason?  

I thought it would be nice to have this small similarity with Qt.  I don't think it breaks anything existing?

**Comment by fr00b0** [comment]
As I explained when closing the pull request (https://github.com/fr00b0/nod/pull/30#issuecomment-1114510935), this will not be merged since I don't think it belongs in the library.

I am not interested in similarities to Qt5. 
Also: how can you say this does not break anything when you have used the preprocessor to define the words "signals" and "slots" in a public header of the library? To me the potential for breakage in code bases using the library is really high.

Anyway, as per my previous comment. This is really easy for a project to implement if desired, without it being part of the library.

**Comment by drewr95** [comment]
I did not get that notification

**Comment by fr00b0** [comment]
No worries. Thank you for contributions and interest in the library.

**Pull request closed without merging**
