### PR TITLE
Added support for CMake build system

### PR DESCRIPTION
**Pull request by oliverdaniell**

### CODE REVIEW

**Comment by oliverdaniell** [comment]
I've added support for CMake while I do some work to add move construct/assign, if you don't want to add support for CMake then I will just cherry pick the move construct/assign work without the CMake additions

**Comment by fr00b0** [comment]
Hello,

I'd rather you removed the CMake configurations from the pull request #19, so the two things are separate.

I'm not sure I'm going to merge CMake support since `nod` is a header only library, and already has premake support for building the tests. I have to think about (or be convinced) it would be worth maintaining multiple solutions.

**Comment by oliverdaniell** [comment]
> I'm not sure I'm going to merge CMake support since nod is a header only library, and already has premake support for building the tests

That's fair enough.  I've added the CMake support to simplify the usage of nod in other CMake projects and [package managers](https://github.com/ruslo/hunter)

```
find_package(nod CONFIG REQUIRED)
target_link_libraries(foo nod::nod)
```
Of course the same argument can be made for meson, build2 etc. so I understand if you don't want to add CMake support.

**Comment by fr00b0** [comment]
Will not add support for CMake at this time. The library is just a single header file, and such should be easy enough to use with CMake anyway.

**Pull request closed without merging**
